disabled_rules:
  - function_parameter_count
  - shorthand_operator
  - nesting
  - void_function_in_ternary
  - closing_brace
  - closure_parameter_position
  - colon
  - comma
  - comment_spacing
  - duplicate_imports
  - empty_parameters
  - implicit_getter
  - leading_whitespace
  - line_length
  - mark
  - no_space_in_method_call
  - opening_brace
  - operator_whitespace
  - redundant_discardable_let
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - statement_position
  - switch_case_alignment
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_break_in_switch
  - unused_closure_parameter
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return

opt_in_rules:
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discarded_notification_center_observer
  - discouraged_object_literal
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - ibinspectable_in_extension
  - last_where
  - legacy_multiple
  - legacy_random
  - lower_acl_than_parent
  - missing_docs
  - multiline_parameters
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_outlet
  - private_swiftui_state
  - prohibited_super_call
  - reduce_into
  - self_binding
  - sorted_first_last
  - static_operator
  - toggle_bool

identifier_name:
  min_length: 2 # For a variable like `id`
  max_length:
    warning: 1000
    error: 1000
  excluded:
    - id

generic_type_name:
  max_length:
    warning: 1000
    error: 1000

type_name:
  max_length:
    warning: 1000
    error: 1000
  excluded:
    - Id

file_length:
  warning: 600

function_body_length:
  warning: 60

cyclomatic_complexity:
  ignores_case_statements: true
